Add generate_announcements command
tamucybersec/CyberHam pull request #30
Opened 2024-08-26 23:58 UTC by deciphr

Generates a boilerplate announcement from Discord events.

2024-08-26 23:59 UTC, deciphr commented
make sure you replace the emoji with the emoji in the server

\:cowboysunglasses:

2024-08-27 00:02 UTC, lilacstella requested changes

2024-08-27 00:02 UTC, lilacstella commented on cyberham/__main__.py
> +# Howdy everyone! <:cowboysunglasses:1277767237037723751>
```suggestion
# Howdy everyone! <:sunglasses_cowboy:916376081576116354>
```

2024-08-27 00:03 UTC, lilacstella commented
honestly LGTM

2024-08-27 00:05 UTC, lilacstella approved these changes

2024-08-27 00:06 UTC, HomeoStasis69 approved these changes
looks good from my end

2024-08-27 00:20 UTC, merged